"""
Django settings for BiomeMarket project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import os
from pathlib import Path
from pathlib import Path
try:
    # cargar variables de entorno desde .env en el BASE_DIR si está presente
    from dotenv import load_dotenv
    load_dotenv()
except Exception:
    # dotenv no instalado o .env no encontrado: continuar usando os.environ
    pass


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-q#r=z+!mg4uhnc#5+)1*h(0e+k&_dnk#xk1ogc+1#z4@@bh(6l'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'productos',
    'accounts',
    'chatbot',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'BiomeMarket.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',

                'productos.context_processors.carrito_context',
            ],
        },
    },
]

WSGI_APPLICATION = 'BiomeMarket.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

PAYPAL_CLIENT_ID = (
    "AdWG2Gxl6HLSVJhP11_pSa21Tv3Z5V43NPBfmd-SZNi3FA_6ZURIC5PZGzVrI_J2Le1HDAUhGNb0K_IL"
)
PAYPAL_CLIENT_SECRET = (
    "EKa2mu19WOBbRJ4h2ais743Azx-onadHxF9D9nscZpXbZeoBtTG84INAhCmCALwBP8hjd0i66Qq1_akt"
)
PAYPAL_MODE = "sandbox"  # o 'live' dependiendo de tu entorno

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'  # ← FIX: Con / al inicio (URL base para templates {% static %})
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')  # ← Para collectstatic en prod (crea carpeta si no existe)
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),  # ← Global: static/css/, static/img/logo.png
    # Si tienes en app: os.path.join(BASE_DIR, 'productos', 'static'),  # App-specific
]  # Lista, no tuple—mejor para múltiples

# Configuración de Media (imágenes subidas por usuarios, e.g., producto.imagen)
MEDIA_URL = '/media/'  # ← Bien, con /
MEDIA_ROOT = BASE_DIR / 'media'  # ← Bien (usa pathlib, OK en Django 3+)

# Para desarrollo: Sirve static/media automáticamente
DEBUG = True  # ← Asegura True en dev

# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field
SESSION_COOKIE_AGE = 1209600
SESSION_SAVE_EVERY_REQUEST = True
CART_SESSION_ID = 'biomarket_carrito'
SESSION_ENGINE = 'django.contrib.sessions.backends.db'
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
# Email (configura esto para enviar correos reales)
# Los valores se leen desde variables de entorno por seguridad.
EMAIL_BACKEND = os.environ.get('DJANGO_EMAIL_BACKEND', 'django.core.mail.backends.smtp.EmailBackend')
EMAIL_HOST = os.environ.get('EMAIL_HOST', 'smtp.gmail.com')
EMAIL_PORT = int(os.environ.get('EMAIL_PORT', 587))
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', '')
EMAIL_USE_TLS = os.environ.get('EMAIL_USE_TLS', 'True').lower() in ('1', 'true', 'yes')
DEFAULT_FROM_EMAIL = os.environ.get('DEFAULT_FROM_EMAIL', 'no-reply@biomarket.local')


